name: Upload and Download Artifacts Between Jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build something and create artifact
        run: |
          echo "This is a test artifact file" > artifact.txt
          # Weitere Build- oder Erstellungsbefehle, die das Artefakt erzeugen

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt
        # Das Artefakt wird unter dem Namen 'my-artifact' hochgeladen.

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Job2 wartet, bis Job1 abgeschlossen ist
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from job1
        uses: actions/download-artifact@v4
        with:
          name: my-artifact  # Das Artefakt, das in Job1 hochgeladen wurde

      - name: Use the downloaded artifact
        run: |
          cat artifact.txt
          # Das heruntergeladene Artefakt wird verwendet
          # In diesem Fall wird es mit 'cat' angezeigt
